# Generated by Django 5.1.2 on 2024-10-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Name', models.CharField(max_length=10)),
                ('accno', models.IntegerField(primary_key='accno', serialize=False)),
                ('amount', models.FloatField()),
                ('interest', models.DateField()),
                ('duedate', models.EmailField(max_length=254)),
            ],
        ),
    ]
